# Generated by Django 4.2.6 on 2023-11-05 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productcategory_name_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='discription',
            new_name='description',
        ),
    ]
